In [96]:
import pandas as pd
import numpy as np

In [97]:
s=pd.Series([10,20,30,40,50])

In [98]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [99]:
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [100]:
s=pd.Series([10,20,30,40,50,'abc'])

In [101]:
s

0     10
1     20
2     30
3     40
4     50
5    abc
dtype: object

In [102]:
s.values

array([10, 20, 30, 40, 50, 'abc'], dtype=object)

In [103]:
s.name="numbers"

In [104]:
s

0     10
1     20
2     30
3     40
4     50
5    abc
Name: numbers, dtype: object

In [105]:
s[0]

10

In [106]:
s[0:2]

0    10
1    20
Name: numbers, dtype: object

In [107]:
index=['apple','banana','strawberry','grapes','orange']

In [108]:
s

0     10
1     20
2     30
3     40
4     50
5    abc
Name: numbers, dtype: object

In [109]:
food_protein={
    "chicken":25.4,
    "mutton":22.5,
    "panner":20.7,
    "soya chunks":30
}

In [110]:
s2=pd.Series(food_protein,name="protein")

In [111]:
s2

chicken        25.4
mutton         22.5
panner         20.7
soya chunks    30.0
Name: protein, dtype: float64

In [112]:
df=s2.to_frame()

In [113]:
df

             protein
chicken         25.4
mutton          22.5
panner          20.7
soya chunks     30.0

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, chicken to soya chunks
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   protein  4 non-null      float64
dtypes: float64(1)
memory usage: 236.0+ bytes

In [115]:
s2>25

chicken         True
mutton         False
panner         False
soya chunks     True
Name: protein, dtype: bool

In [116]:
s2<30

chicken         True
mutton          True
panner          True
soya chunks    False
Name: protein, dtype: bool

In [117]:
print((s2>20) & (s2<25))

chicken        False
mutton          True
panner          True
soya chunks    False
Name: protein, dtype: bool

In [118]:
df

             protein
chicken         25.4
mutton          22.5
panner          20.7
soya chunks     30.0

In [119]:
df["mutton"] = 24

In [120]:
df

             protein  mutton
chicken         25.4      24
mutton          22.5      24
panner          20.7      24
soya chunks     30.0      24

In [121]:
s2

chicken        25.4
mutton         22.5
panner         20.7
soya chunks    30.0
Name: protein, dtype: float64

In [122]:
s2["mutton"]=24

In [123]:
s2

chicken        25.4
mutton         24.0
panner         20.7
soya chunks    30.0
Name: protein, dtype: float64

In [124]:
s2["mutton"]=22

In [125]:
s2

chicken        25.4
mutton         22.0
panner         20.7
soya chunks    30.0
Name: protein, dtype: float64

In [126]:
s2.drop("panner")

chicken        25.4
mutton         22.0
soya chunks    30.0
Name: protein, dtype: float64

In [127]:
s2

chicken        25.4
mutton         22.0
panner         20.7
soya chunks    30.0
Name: protein, dtype: float64

In [128]:
s2.drop("soya chunks")

chicken    25.4
mutton     22.0
panner     20.7
Name: protein, dtype: float64

In [129]:
s2

chicken        25.4
mutton         22.0
panner         20.7
soya chunks    30.0
Name: protein, dtype: float64

In [130]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])

print(ser.notnull().sum())

3

In [131]:
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [132]:
import pandas as pd

In [133]:
df=pd.DataFrame(data)

In [134]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [135]:
df.head()

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN

In [136]:
df.tail()

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [137]:
df.head(3)

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [138]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [139]:
df.iloc[1:3,:2]

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [140]:
df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [141]:
print(df[["Age","Department"]])

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [142]:
df.drop("Age",axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [143]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [144]:
df.shape

(6, 4)

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [146]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [147]:
df["Salary"]=df["Salary"]-5000

In [148]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  45000.0
1      Bob  30.0         IT  55000.0
2  Charlie  35.0    Finance  65000.0
3    David   NaN         IT  57000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  45000.0

In [149]:
df.rename(columns={"Department": "Dept"}, inplace=True)

In [150]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  45000.0
1      Bob  30.0       IT  55000.0
2  Charlie  35.0  Finance  65000.0
3    David   NaN       IT  57000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  45000.0

In [151]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [152]:
df["Salary"].unique()

array([45000., 55000., 65000., 57000.,    nan])

In [153]:
df["Age"].unique()

array([25., 30., 35., nan, 29.])

In [154]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [155]:
df["Promoted_salary"]=df["Salary"]*10

In [156]:
df

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
3    David   NaN       IT  57000.0         570000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  45000.0         450000.0

In [157]:
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted_salary    1
dtype: int64

In [158]:
df.dropna()

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
5    Alice  25.0       HR  45000.0         450000.0

In [159]:
df

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
3    David   NaN       IT  57000.0         570000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  45000.0         450000.0

In [160]:
df.dropna(how="any")

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
5    Alice  25.0       HR  45000.0         450000.0

In [161]:
df.dropna(how="all")

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
3    David   NaN       IT  57000.0         570000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  45000.0         450000.0

In [162]:
df

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
3    David   NaN       IT  57000.0         570000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  45000.0         450000.0

In [163]:
df.fillna(0)

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
3    David   0.0       IT  57000.0         570000.0
4      Eve  29.0       HR      0.0              0.0
5    Alice  25.0       HR  45000.0         450000.0

In [164]:
df['Age'].fillna(df['Age'].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [165]:
df['Salary'].fillna(df["Salary"].median())

0    45000.0
1    55000.0
2    65000.0
3    57000.0
4    55000.0
5    45000.0
Name: Salary, dtype: float64

In [166]:
df

      Name   Age     Dept   Salary  Promoted_salary
0    Alice  25.0       HR  45000.0         450000.0
1      Bob  30.0       IT  55000.0         550000.0
2  Charlie  35.0  Finance  65000.0         650000.0
3    David   NaN       IT  57000.0         570000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  45000.0         450000.0

In [167]:
df['Age'].fillna(method='ffill')

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\1265906299.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method='ffill')

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [168]:
df['Age'].fillna(method='bfill')

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\3224957626.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method='bfill')

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [169]:
df['Name'].replace("Charlie","Rose",inplace=True)

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\2612872993.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].replace("Charlie","Rose",inplace=True)

In [170]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0         450000.0
1    Bob  30.0       IT  55000.0         550000.0
2   Rose  35.0  Finance  65000.0         650000.0
3  David   NaN       IT  57000.0         570000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  45000.0         450000.0

In [171]:
df["Name"].replace("Rose", "Vinay", inplace=True)

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\2889432012.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].replace("Rose", "Vinay", inplace=True)

In [172]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0         450000.0
1    Bob  30.0       IT  55000.0         550000.0
2  Vinay  35.0  Finance  65000.0         650000.0
3  David   NaN       IT  57000.0         570000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  45000.0         450000.0

In [173]:
df["Age after 10years"]=df["Age"]+10

In [174]:
df

    Name   Age     Dept   Salary  Promoted_salary  Age after 10years
0  Alice  25.0       HR  45000.0         450000.0               35.0
1    Bob  30.0       IT  55000.0         550000.0               40.0
2  Vinay  35.0  Finance  65000.0         650000.0               45.0
3  David   NaN       IT  57000.0         570000.0                NaN
4    Eve  29.0       HR      NaN              NaN               39.0
5  Alice  25.0       HR  45000.0         450000.0               35.0

In [175]:
df.drop("Age after 10years",axis=1)

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0         450000.0
1    Bob  30.0       IT  55000.0         550000.0
2  Vinay  35.0  Finance  65000.0         650000.0
3  David   NaN       IT  57000.0         570000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  45000.0         450000.0

In [176]:
df_dup=df[df.duplicated()]

In [177]:
df_dup

    Name   Age Dept   Salary  Promoted_salary  Age after 10years
5  Alice  25.0   HR  45000.0         450000.0               35.0

In [178]:
df_dup=df[df.duplicated(keep="first")]

In [179]:
df_dup

    Name   Age Dept   Salary  Promoted_salary  Age after 10years
5  Alice  25.0   HR  45000.0         450000.0               35.0

In [180]:
df_dup=df[df.duplicated(keep="last")]

In [181]:
df_dup

    Name   Age Dept   Salary  Promoted_salary  Age after 10years
0  Alice  25.0   HR  45000.0         450000.0               35.0

In [182]:
df=df.drop_duplicates()

In [183]:
df

    Name   Age     Dept   Salary  Promoted_salary  Age after 10years
0  Alice  25.0       HR  45000.0         450000.0               35.0
1    Bob  30.0       IT  55000.0         550000.0               40.0
2  Vinay  35.0  Finance  65000.0         650000.0               45.0
3  David   NaN       IT  57000.0         570000.0                NaN
4    Eve  29.0       HR      NaN              NaN               39.0

In [184]:
df.drop("Age after 10years",axis=1,inplace=True)

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\106554741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("Age after 10years",axis=1,inplace=True)

In [185]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0         450000.0
1    Bob  30.0       IT  55000.0         550000.0
2  Vinay  35.0  Finance  65000.0         650000.0
3  David   NaN       IT  57000.0         570000.0
4    Eve  29.0       HR      NaN              NaN

In [186]:
 df['Promoted_salary']=df['Promoted_salary'].apply(lambda x:x/10 if x>65000 else x)

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\771673374.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Promoted_salary']=df['Promoted_salary'].apply(lambda x:x/10 if x>65000 else x)

In [187]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0          45000.0
1    Bob  30.0       IT  55000.0          55000.0
2  Vinay  35.0  Finance  65000.0          65000.0
3  David   NaN       IT  57000.0          57000.0
4    Eve  29.0       HR      NaN              NaN

In [188]:
def multiply_age(x):
    return x*2
df['Age']=df['Age'].apply(multiply_age)

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\479766385.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].apply(multiply_age)

In [189]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  50.0       HR  45000.0          45000.0
1    Bob  60.0       IT  55000.0          55000.0
2  Vinay  70.0  Finance  65000.0          65000.0
3  David   NaN       IT  57000.0          57000.0
4    Eve  58.0       HR      NaN              NaN

In [190]:
df['Age']=df['Age'].apply(lambda x:x/2)

C:\Users\VEERENDRA\AppData\Local\Temp\ipykernel_18512\1971227271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].apply(lambda x:x/2)

In [191]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0          45000.0
1    Bob  30.0       IT  55000.0          55000.0
2  Vinay  35.0  Finance  65000.0          65000.0
3  David   NaN       IT  57000.0          57000.0
4    Eve  29.0       HR      NaN              NaN

In [199]:
data2={"Dept":["HR","IT","Finance"],"Location":["New york","San Franchise","Chicago"],"Manager":["Laura","Steve","Niha"]}

In [200]:
df2=pd.DataFrame(data2)

In [201]:
df

    Name   Age     Dept   Salary  Promoted_salary
0  Alice  25.0       HR  45000.0          45000.0
1    Bob  30.0       IT  55000.0          55000.0
2  Vinay  35.0  Finance  65000.0          65000.0
3  David   NaN       IT  57000.0          57000.0
4    Eve  29.0       HR      NaN              NaN

In [202]:
df2

      Dept       Location Manager
0       HR       New york   Laura
1       IT  San Franchise   Steve
2  Finance        Chicago    Niha

In [203]:
pd.concat([df,df2])

    Name   Age     Dept   Salary  Promoted_salary       Location Manager
0  Alice  25.0       HR  45000.0          45000.0            NaN     NaN
1    Bob  30.0       IT  55000.0          55000.0            NaN     NaN
2  Vinay  35.0  Finance  65000.0          65000.0            NaN     NaN
3  David   NaN       IT  57000.0          57000.0            NaN     NaN
4    Eve  29.0       HR      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       New york   Laura
1    NaN   NaN       IT      NaN              NaN  San Franchise   Steve
2    NaN   NaN  Finance      NaN              NaN        Chicago    Niha

In [204]:
pd.concat([df,df2],axis=1)

,Name,Age,Dept,Salary,Promoted_salary,Dept,Location,Manager
0,Alice,25.0,HR,45000.0,45000.0,HR,New york,Laura
1,Bob,30.0,IT,55000.0,55000.0,IT,San Franchise,Steve
2,Vinay,35.0,Finance,65000.0,65000.0,Finance,Chicago,Niha
3,David,NaN,IT,57000.0,57000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [205]:
pd.merge(df,df2,on="Dept")

    Name   Age     Dept   Salary  Promoted_salary       Location Manager
0  Alice  25.0       HR  45000.0          45000.0       New york   Laura
1    Bob  30.0       IT  55000.0          55000.0  San Franchise   Steve
2  Vinay  35.0  Finance  65000.0          65000.0        Chicago    Niha
3  David   NaN       IT  57000.0          57000.0  San Franchise   Steve
4    Eve  29.0       HR      NaN              NaN       New york   Laura

In [207]:
data=pd.read_csv(r"C:\Users\VEERENDRA\Downloads\archive\data.csv")

In [208]:
data

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [212]:
data.shape

(4600, 18)

In [214]:
data.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [216]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [217]:
data["date"]=pd.to_datetime(data["date"])

In [218]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   datetime64[ns]
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(9), object(4)
memory usage: 647.0+ KB